/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type ConstructorFunction =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type FallbackFunction =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type NormalFunction =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type ABI = (Event | ConstructorFunction | FallbackFunction | ReceiveFunction | NormalFunction)[];

export interface Event {
  type: "event";
  name: Name;
  inputs: EventParameter[];
  anonymous: boolean;
}
export interface EventParameter {
  [k: string]: unknown;
}
export interface ReceiveFunction {
  type: "receive";
  stateMutability: "payable";
}
